/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.dokaattila.maven.calorie.calculator;

import java.awt.Image;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author dokaa
 */
public class KaloriaSzamlaloFoablak extends javax.swing.JFrame {

    private DefaultListModel<Meal> listModel = new DefaultListModel<>();

    /**
     * Creates new form KaloriaSzamlaloFoablak
     *
     * @throws kaloriaszamlalo.KaloriaDAOException
     * @throws java.sql.SQLException
     */
    public KaloriaSzamlaloFoablak() throws KaloriaDAOException, SQLException {
        initComponents();
        ImageIcon img = new ImageIcon("bg.jpg");
        Image img2 = img.getImage().getScaledInstance(jLabelBg.getWidth(), jLabelBg.getHeight(), 1);
        ImageIcon img3 = new ImageIcon(img2);
        jLabelBg.setIcon(img3);
        mealList.setModel(listModel);
        for (Meal m : Controller.getAllMeal()) {
            listModel.addElement(m);

        }
        DecimalFormat f = new DecimalFormat("##.00");
        this.sumCarbLabel.setText(f.format(Controller.updateWindow().get("sumCarb")) + " g");
        this.sumCalLabel.setText(f.format(Controller.updateWindow().get("sumCal")) + " kcal");
        this.sumFatLabel.setText(f.format(Controller.updateWindow().get("sumFat")) + " g");
        this.sumProtLabel.setText(f.format(Controller.updateWindow().get("sumProt")) + " g");
        this.avgCarbLabel.setText(f.format(Controller.updateWindow().get("avgCarb")) + " g");
        this.avgCalLabel.setText(f.format(Controller.updateWindow().get("avgCal")) + " kcal");
        this.avgFatLabel.setText(f.format(Controller.updateWindow().get("avgFat")) + " g");
        this.avgProtLabel.setText(f.format(Controller.updateWindow().get("avgProt")) + " g");

    }

    public DefaultListModel<Meal> getListModel() {
        return listModel;
    }

    public void setListModel(DefaultListModel<Meal> listModel) {
        this.listModel = listModel;
    }

    public JLabel getSumCalLabel() {
        return sumCalLabel;
    }

    public JLabel getSumCarbLabel() {
        return sumCarbLabel;
    }

    public JLabel getSumFatLabel() {
        return sumFatLabel;
    }

    public JLabel getSumProtLabel() {
        return sumProtLabel;
    }

    public JLabel getAvgCalLabel() {
        return avgCalLabel;
    }

    public JLabel getAvgCarbLabel() {
        return avgCarbLabel;
    }

    public JLabel getAvgFatLabel() {
        return avgFatLabel;
    }

    public JLabel getAvgProtLabel() {
        return avgProtLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealList = new javax.swing.JList<>();
        newMealButton = new javax.swing.JButton();
        editMealButton = new javax.swing.JButton();
        deleteMealButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        avgCalLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        avgProtLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        avgFatLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        avgCarbLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sumProtLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sumFatLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sumCarbLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sumCalLabel = new javax.swing.JLabel();
        resetData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mealList.setToolTipText("");
        jScrollPane1.setViewportView(mealList);

        newMealButton.setText("Új étel");
        newMealButton.setMaximumSize(new java.awt.Dimension(80, 23));
        newMealButton.setMinimumSize(new java.awt.Dimension(80, 23));
        newMealButton.setPreferredSize(new java.awt.Dimension(80, 23));
        newMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMealButtonActionPerformed(evt);
            }
        });

        editMealButton.setText("Módosít");
        editMealButton.setMaximumSize(new java.awt.Dimension(80, 23));
        editMealButton.setMinimumSize(new java.awt.Dimension(80, 23));
        editMealButton.setPreferredSize(new java.awt.Dimension(80, 23));
        editMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMealButtonActionPerformed(evt);
            }
        });

        deleteMealButton.setText("Törlés");
        deleteMealButton.setMaximumSize(new java.awt.Dimension(80, 23));
        deleteMealButton.setMinimumSize(new java.awt.Dimension(80, 23));
        deleteMealButton.setPreferredSize(new java.awt.Dimension(80, 23));
        deleteMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMealButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Napi átlag:");

        avgCalLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        avgCalLabel.setText("xxx");

        jLabel3.setText("Kalória:");

        jLabel2.setText("|");

        jLabel4.setText("Fehérje:");

        avgProtLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        avgProtLabel.setText("xxx");

        jLabel6.setText("|");

        jLabel7.setText("Zsírok:");

        avgFatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        avgFatLabel.setText("xxx");

        jLabel9.setText("|");
        jLabel9.setToolTipText("");

        jLabel10.setText("Szénhidrát:");

        avgCarbLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        avgCarbLabel.setText("xxx");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Mai fogyasztás:");

        jLabel8.setText("Fehérje:");

        sumProtLabel.setText("xxx");

        jLabel12.setText("Zsírok:");

        sumFatLabel.setText("xxx");

        jLabel14.setText("Szénhidrát:");

        sumCarbLabel.setText("xxx");

        jLabel16.setText("Kalória:");

        sumCalLabel.setText("xxx");

        resetData.setText("Nulláz");
        resetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avgCalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avgProtLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avgFatLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sumProtLabel)
                                    .addComponent(sumFatLabel)
                                    .addComponent(sumCarbLabel)
                                    .addComponent(sumCalLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avgCarbLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetData)))
                        .addGap(112, 112, 112)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBg, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(avgCalLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(avgProtLabel)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(avgFatLabel)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(avgCarbLabel)
                    .addComponent(resetData))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(sumProtLabel))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(sumFatLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(sumCarbLabel))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(sumCalLabel))
                                .addGap(0, 83, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMealButtonActionPerformed
        try {
            // TODO add your handling code here:
            Controller.newMeal();
        } catch (KaloriaDAOException | SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_newMealButtonActionPerformed

    private void deleteMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMealButtonActionPerformed
        Object[] options = {"Igen", "Mégse"};
        int input = JOptionPane.showOptionDialog(rootPane, "Biztosan törölni szeretnéd a kiválasztott elemet?", "Megerősítés", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (input == 0) {
            try {
                Controller.deleteMeal(mealList.getSelectedValue().getMealID());
            } catch (KaloriaDAOException | SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }//GEN-LAST:event_deleteMealButtonActionPerformed

    private void editMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMealButtonActionPerformed
        // TODO add your handling code here:
        try {
            Controller.editMeal(mealList.getSelectedValue().getMealID(), Optional.of(mealList.getSelectedValue()));
        } catch (KaloriaDAOException | SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_editMealButtonActionPerformed

    private void resetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDataActionPerformed
        Object[] options = {"Igen", "Mégse"};
        try {
            int input = JOptionPane.showOptionDialog(rootPane, "Biztosan törölni szeretnéd az előzményeket?", "Megerősítés", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (input == 0) {
                Controller.setZero();
            }
        } catch (KaloriaDAOException | SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_resetDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaloriaSzamlaloFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaloriaSzamlaloFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaloriaSzamlaloFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaloriaSzamlaloFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new KaloriaSzamlaloFoablak().setVisible(true);
                } catch (KaloriaDAOException ex) {
                    Logger.getLogger(KaloriaSzamlaloFoablak.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(KaloriaSzamlaloFoablak.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgCalLabel;
    private javax.swing.JLabel avgCarbLabel;
    private javax.swing.JLabel avgFatLabel;
    private javax.swing.JLabel avgProtLabel;
    private javax.swing.JButton deleteMealButton;
    private javax.swing.JButton editMealButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Meal> mealList;
    private javax.swing.JButton newMealButton;
    private javax.swing.JButton resetData;
    private javax.swing.JLabel sumCalLabel;
    private javax.swing.JLabel sumCarbLabel;
    private javax.swing.JLabel sumFatLabel;
    private javax.swing.JLabel sumProtLabel;
    // End of variables declaration//GEN-END:variables

    private static class ConfirmDialogInFrame {

        public ConfirmDialogInFrame() {
        }
    }
}
